apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: meridian-app
  labels:
    app: account-service
spec:
  type: ClusterIP
  selector:
    app: account-service
  ports:
    - name: http
      port: 8002
      targetPort: http