apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fx-service
  namespace: meridian-app
  labels:
    app: fx-service
spec:
  selector:
    matchLabels:
      app: fx-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
