# Local only. In EKS these are RDS, ElastiCache, and MSK or Strimzi.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: meridian-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: meridian_app
            - name: POSTGRES_PASSWORD
              value: MeridianDev2024!
            - name: POSTGRES_DB
              value: postgres
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: meridian-app
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: meridian-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: meridian-app
spec:
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: 6379
