apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.nameOverride }}
  ports:
    - name: http
      port: {{ .Values.port }}
      targetPort: http
