nameOverride: payment-service
namespace: meridian-money
tier: "1"
port: 8004
replicas: 3

image:
  repository: meridian-pay/payment-service

strategy:
  maxSurge: 1
  maxUnavailable: 0

terminationGracePeriodSeconds: 60

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 14
  targetCPUUtilizationPercentage: 65
  scaleUpPercent: 100
  scaleUpPeriodSeconds: 30
  scaleDownStabilizationSeconds: 300

podDisruptionBudget:
  enabled: true
  minAvailable: 2

env:
  DB_HOST: postgres.meridian-app.svc.cluster.local
  DB_PORT: "5432"
  DB_NAME: payment_db
  REDIS_HOST: redis.meridian-app.svc.cluster.local
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP: kafka.meridian-app.svc.cluster.local:9092
  LEDGER_SERVICE_URL: http://ledger-service.meridian-money.svc.cluster.local:8005
  PARTNER_BANK_URL: http://partner-bank-sandbox.meridian-app.svc.cluster.local:9100

envFromSecret:
  DB_PASSWORD:
    name: payment-db-credentials
    key: password
