apiVersion: v1
kind: Service
metadata:
  name: ledger-service
  namespace: meridian-money
  labels:
    app: ledger-service
spec:
  type: ClusterIP
  selector:
    app: ledger-service
  ports:
    - name: http
      port: 8005
      targetPort: http